### ISSUE TITLE
about timm version

### ISSUE THREAD

**Issue by myhakureimu** [XueJiang16/NegLabel#4]
Could the author kindly share the version of timm used in this repo? I tried the code with latest timm but there is bug reported:

from timm.models import create_model, apply_test_time_pool, load_checkpoint, is_model, list_models, set_fast_norm
ImportError: cannot import name 'apply_test_time_pool' from 'timm.models' (/usr/miniconda3/envs/neglabel/lib/python3.8/site-packages/timm/models/__init__.py)

So I guess it's due to version mismatch.

**Comment by XueJiang16** [comment]
I used timm 0.7.0.dev0.

**Comment by myhakureimu** [comment]
Thank you for the answer!

**Comment by JB0527** [comment]
I am leaving a message in the hope that it will be helpful.
There is no 0.7.0.dev0. so  I used timm 0.6.13 ....

**Comment by wtrudy** [comment]
> I am leaving a message in the hope that it will be helpful. There is no 0.7.0.dev0. so I used timm 0.6.13 ....

Why do I use 0.6.13 still have this ImportError

**Comment by glhr** [comment]
`timm=0.8.0.dev0` works for me
