### ISSUE TITLE
About Nvidia Driver

### ISSUE THREAD

**Issue by myhakureimu** [XueJiang16/NegLabel#5]
May I ask for the version of Nvidia Driver and GPU? Thanks!

the repo said: conda create -n open-mmlab python=3.8 pytorch==1.10 torchvision==0.11.2 cudatoolkit=11.3 -c pytorch -y

However, I'm not able to perform this line on ubuntu 22.04.

**Comment by XueJiang16** [comment]
I used 3090Ti and Ubuntu 20.04.4 LTS with  Driver Version: 535.161.07.

**Comment by myhakureimu** [comment]
Thank you for sharing!

I'm using google cloud platform. I do not know why but the repo's Pytorch installation does not work for me. I figure out the setting works as follows for the other researchers:

22.04 ubuntu
sudo apt update
sudo apt install nvidia-driver-535-server -y
sudo reboot

curl -O https://repo.anaconda.com/archive/Anaconda3-2023.09-0-Linux-x86_64.sh
bash Anaconda3-2023.09-0-Linux-x86_64.sh 

source /home/user/anaconda3/bin/activate
conda update conda -y
conda update --all -y

conda create -n open-mmlab python=3.8 -c conda-forge -y
conda activate open-mmlab
conda install pytorch=1.10 torchvision=0.11.2 cudatoolkit=11.3 -c pytorch -c conda-forge


pip install openmim
git clone https://github.com/XueJiang16/NegLabel.git
cd NegLabel
mim install -e .
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git
pip install -r requirements.txt
pip install timm==0.6.13
conda install imgaug -y
bash ./run.sh
