### ISSUE TITLE
meta/val_labeled.txt

### ISSUE THREAD

**Issue by myhakureimu** [XueJiang16/NegLabel#6]
I did:
bash ./run.sh

however I encountered:
FileNotFoundError: [Errno 2] No such file or directory: './data/meta/val_labeled.txt'

May the author provide the way to get the file meta/val_labeled.txt?

**Comment by JB0527** [comment]
Same error, too...

**Comment by XueJiang16** [comment]
This is the Text Annotation File of ImageNet-1k val set. You can download from https://mmpretrain.readthedocs.io/en/latest/user_guides/dataset_prepare.html.

**Comment by myhakureimu** [comment]
I tried it and it works. Thank you!
