### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/ood_data/Textures/dtd/images_collate'

### ISSUE THREAD

**Issue by myhakureimu** [XueJiang16/NegLabel#7]
As the repo guides, I go to [MOS](https://arxiv.org/pdf/2105.01879.pdf) to download and unzip the four OOD datasets [iNaturalist](https://arxiv.org/pdf/1707.06642.pdf), [SUN](https://vision.princeton.edu/projects/2010/SUN/paper.pdf), [Places](http://places2.csail.mit.edu/PAMI_places.pdf), and [Textures](https://arxiv.org/pdf/1311.3618.pdf). Then I run bash ./run.sh.

However, I encountered the error in the title. I checked the data Textures from [MOS](https://arxiv.org/pdf/2105.01879.pdf), and I think the data folder structure of [MOS](https://arxiv.org/pdf/2105.01879.pdf) is different from the data Textures used by the authors. May the author point out a link to the data Textures used?

**Comment by XueJiang16** [comment]
I changed the filefold architeture and  put all images into the same directiory.
