### ISSUE TITLE
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: './data/val/ILSVRC2012_val_00007053.JPEG'

### ISSUE THREAD

**Issue by JB0527** [XueJiang16/NegLabel#8]
I keep encountering issues with the data file structure. Could you provide an overall data file structure?

Thank you for your attention to my issue.
Sincerely,

**Comment by XueJiang16** [comment]
I do not change the data  file structure of ImageNet-1k val set, and I have this image `ILSVRC2012_val_00007053.JPEG` in my dataset.

**Comment by JB0527** [comment]
I finished building all data file structures and ran the code exactly.

Thank u!
